version: '3'
services:
  spring-boot-docker-app:
    image: spring-boot-docker-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8181
    volumes:
      - /storage/spring-boot-docker

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'aset_spring_project'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'aset1999'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: