version: '3.8'
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: windows/amd64
    image: "mysql:8"
    restart: always
    ports:
      - 3306:3307
    environment:
      MYSQL_DATABASE: aset-spring-project
      MYSQL_USER: aset1999
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root


